name: CI

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get version
        run: echo "VERSION=`grep '^version' Cargo.toml| egrep -o '[0-9]\.[0-9]\.[0-9]'`" >> $GITHUB_ENV

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: kkdm/ip-update
          tags: ${{ env.VERSION }},latest

